// Arabic (RTL) - Algeria Localization
export const arStrings = {
  // App
  appName: 'وصلني',

  // Auth
  auth: {
    enterTheFleet: 'ادخل\nالأسطول.',
    authenticateBiometric: 'قم بالمصادقة عبر الرابط البيومتري الآمن للوصول إلى مركبتك، تعيينات المسار النشط، ومحفظة الأرباح.',
    sensorActive: 'المستشعر نشط',
    tapScanner: 'اضغط على الماسح للتحقق من الهوية',
    orAuthenticateVia: 'أو المصادقة عبر',
    continue: 'متابعة',
    verifyIdentity: 'تحقق\nمن الهوية.',
    enterMobileNumber: 'أدخل رقم هاتفك لتلقي رمز مرور آمن لمرة واحدة.',
    resendCodeIn: 'إعادة إرسال الرمز خلال',
    resendCode: 'إعادة إرسال الرمز',
    verify: 'تحقق',
  },

  // Onboarding
  onboarding: {
    identityVerification: 'التحقق من الهوية',
    basics: 'الأساسيات',
    identity: 'الهوية',
    vehicle: 'المركبة',
    personalInformation: 'المعلومات الشخصية',
    fullLegalName: 'الاسم الكامل القانوني',
    asItAppearsOnLicense: 'كما يظهر في رخصتك',
    emailAddress: 'عنوان البريد الإلكتروني',
    youAtDomain: 'you@domain.com',
    homeAddress: 'عنوان المنزل',
    streetAddress: 'عنوان الشارع',
    city: 'المدينة',
    zip: 'الرمز البريدي',
    driversLicense: 'رخصة القيادة',
    uploadClearImages: 'قم بتحميل صور واضحة ومضيئة جيداً لبطاقة هويتك الرسمية.',
    frontSide: 'الوجه الأمامي',
    backSide: 'الوجه الخلفي',
    livenessCheck: 'التحقق من الحيوية',
    takeQuickSelfie: 'التقط صورة سريعة لمطابقتها مع هويتك.',
    captureSelfie: 'التقط صورة شخصية',
    saveDraft: 'حفظ المسودة',
    continueToVehicle: 'متابعة إلى المركبة',
    vehicleIdentity: 'هوية\nالمركبة.',
    precisionParamount: 'الدقة أمر بالغ الأهمية. سجل تفاصيل مركبتك لضمان تجربة سلسة لعملائنا.',
    makeAndModel: 'الصانع والطراز',
    make: 'الصانع',
    makePlaceholder: 'مثال: تويوتا',
    model: 'الطراز',
    modelPlaceholder: 'مثال: كامري',
    year: 'السنة',
    yearPlaceholder: 'مثال: 2024',
    licensePlate: 'لوحة الترخيص',
    licensePlatePlaceholder: 'مثال: ABC-1234',
    documentation: 'الوثائق',
    uploadClearCopies: 'قم بتحميل نسخ واضحة ومقروءة من وثائقك الحالية.',
    proofOfInsurance: 'إثمان التأمين',
    tapToUpload: 'اضغط لتحميل الملف',
    tapToUploadFile: 'اضغط لتحميل الملف',
    vehicleRegistration: 'تسجيل المركبة',
    continueToBackgroundCheck: 'متابعة إلى فحص الخلفية',
    step2Of4: 'الخطوة 2 من 4',
  },

  // Main
  main: {
    readyToDrive: 'جاهز للقيادة؟',
    goOnline: 'ابدأ العمل',
    goOffline: 'توقف عن العمل',
    highDemand: 'طلب عالي في منطقتك حالياً.',
    todaysEarnings: 'أرباح اليوم',
    todayEarnings: 'أرباح اليوم',
    vsYesterday: 'مقارنة بالأمس',
    currentRating: 'التقييم الحالي',
    tripsCompleted: 'الرحلات المكتملة',
    home: 'الرئيسية',
    activity: 'النشاط',
    wallet: 'المحفظة',
    profile: 'الملف الشخصي',
    opportunities: 'الفرص',
    highDemandDowntown: 'طلب عالي: وسط المدينة',
    slideForEmergency: 'اسحب للطوارئ',
    earnings: 'الأرباح',
    trips: 'الرحلات',
    safety: 'السلامة',
  },

  // Ride Request
  rideRequest: {
    seconds: 'ثانية',
    blackSUV: 'اقتصادية',
    premiumRider: 'راكب موثق',
    pickup: 'نقطة الالتقاط',
    minsAway: 'دقيقة',
    estFare: 'الأجر المقدر',
    trip: 'رحلة',
    reject: 'رفض',
    acceptRide: 'قبول الرحلة',
  },

  // Ride Navigation
  rideNavigation: {
    pickup: 'نقطة الالتقاط',
    dropoff: 'الوجهة',
    fare: 'السعر',
    distance: 'المسافة',
    eta: 'الوقت',
    completeRide: 'إنهاء الرحلة',
    cancelRide: 'إلغاء الرحلة',
    cancelConfirm: 'هل أنت متأكد من إلغاء هذه الرحلة؟',
    rideCompleted: 'تمت الرحلة',
    rideCompletedDescription: 'تمت إضافة الأرباح إلى محفظتك.',
    noActiveRide: 'لا توجد رحلة نشطة',
  },

  // Earnings
  earnings: {
    title: 'الأرباح',
    balance: 'رصيد السائق',
    availableBalance: 'الرصيد المتاح والسجل',
    cashOutNow: 'سحب',
    withdraw: 'تحويل',
    tripEarnings: 'أرباح الرحلات',
    tips: 'الإكراميات',
    bonuses: 'المكافآت',
    recentActivity: 'النشاط الأخير',
    viewAll: 'عرض كل النشاط',
    tripTo: 'رحلة إلى',
    includesTip: 'تشمل إكرامية',
    weeklyPayout: 'الدفع الأسبوعي',
    processed: 'تمت المعالجة',
    paymentMethods: 'طرق الدفع',
    defaultCard: 'بطاقة بنكية',
    cashPayment: 'نقداً',
    default: 'افتراضي',
    addNewMethod: 'إضافة طريقة جديدة',
    addFunds: 'إضافة رصيد',
  },

  // Trip History
  tripHistory: {
    title: 'سجل الرحلات',
    reviewPerformance: 'راجع أداءك السابق وأرباحك.',
    weeklyEarnings: 'الأرباح الأسبوعية',
    trips: 'الرحلات',
    onlineHours: 'ساعات العمل',
    vsLastWeek: 'مقارنة بالأسبوع الماضي',
    performance: 'الأداء',
    acceptanceRate: 'معدل القبول',
    cancellationRate: 'معدل الإلغاء',
    recentTrips: 'الرحلات الأخيرة',
    filter: 'تصفية',
    luxeBlack: 'لوكس الأسود',
    luxeStandard: 'لوكس العادي',
    luxeSUV: 'لوكس دفع رباعي',
    loadMoreTrips: 'تحميل المزيد من الرحلات',
  },

  // Common
  common: {
    save: 'حفظ',
    edit: 'تعديل',
    delete: 'حذف',
    cancel: 'إلغاء',
    confirm: 'تأكيد',
    back: 'رجوع',
    next: 'التالي',
    done: 'تم',
    loading: 'جاري التحميل...',
    error: 'خطأ',
    success: 'نجح',
    retry: 'إعادة المحاولة',
  },

  // Drafts
  drafts: {
    title: 'المسودات',
    subtitle: 'طلباتك المحفوظة',
    personalInfoDraft: 'المعلومات الشخصية',
    savedYesterday: 'محفوظ بالأمس',
    noDrafts: 'لا توجد مسودات بعد',
    noDraftsDescription: 'ابدأ طلباً جديداً للبدء',
    startNewApplication: 'بدء طلب جديد',
  },

  // Settings
  settings: {
    title: 'الحساب',
    rating: 'التقييم',
    safetySecurity: 'الأمان والحماية',
    twoFactor: 'المصادقة الثنائية',
    twoFactorDesc: 'تأمين حسابك برموز SMS',
    on: 'مفعّل',
    off: 'معطّل',
    emergencyContacts: 'جهات اتصال الطوارئ',
    emergencyContactsDesc: 'إدارة جهات الاتصال الموثوقة',
    preferences: 'التفضيلات',
    pushNotifications: 'الإشعارات الفورية',
    pushNotificationsDesc: 'تحديثات الرحلات والعروض',
    language: 'اللغة',
    english: 'English',
    arabic: 'العربية',
    selectLanguage: 'اختر اللغة',
    cancel: 'إلغاء',
    supportLegal: 'الدعم والقانون',
    helpCenter: 'مركز المساعدة',
    termsPrivacy: 'الشروط والخصوصية',
    logOut: 'تسجيل الخروج',
  },

  // Terms of Service
  termsOfService: {
    title: 'شروط الخدمة',
    lastUpdated: 'آخر تحديث: يناير 2024',
    intro: 'باستخدام وصالني، أنت توافق على هذه الشروط. يرجى قراءتها بعناية.',
    acceptance: 'قبول الشروط',
    acceptanceText: 'باستخدام خدمتنا، أنت توافق على الالتزام بهذه الشروط.',
    userResponsibilities: 'مسؤوليات المستخدم',
    responsibilityText: 'أنت توافق على استخدام خدمتنا بمسؤولية ووفقاً للقوانين المعمول بها.',
    paymentTerms: 'شروط الدفع',
    paymentText: 'تتم معالجة الدفع في نهاية كل رحلة. أنت توافق على دفع جميع الرسوم المطبقة.',
    cancellation: 'سياسة الإلغاء',
    cancellationText: 'يمكنك إلغاء رحلتك في أي وقت قبل الاستلام دون رسوم.',
  },

  // Help
  help: {
    title: 'المساعدة والدعم',
    subtitle: 'كيف يمكننا مساعدتك؟',
    faq: 'الأسئلة الشائعة',
    paymentIssues: 'مشاكل الدفع',
    rideIssues: 'مشاكل الرحلة',
    safetyConcerns: 'مخاوف السلامة',
    contactSupport: 'تحتاج مساعدة فورية؟',
    callSupport: 'اتصل بالدعم',
  },

  // Notifications
  notifications: {
    title: 'الإشعارات',
    preferences: 'تفضيلات الإشعارات',
    history: 'سجل الإشعارات',
    rideUpdates: 'تحديثات الرحلات',
    rideUpdatesDesc: 'إشعارات حالة الرحلة',
    promotions: 'العروض',
    promotionsDesc: 'عروض وخصومات خاصة',
    messages: 'الرسائل',
    messagesDesc: 'رسائل الركاب والدعم',
    accountActivity: 'نشاط الحساب',
    accountActivityDesc: 'تحديثات الأمان والحساب',
    rideCompleted: 'اكتملت الرحلة',
    rideCompletedMsg: 'تم إكمال رحلتك إلى المطار',
    specialOffer: 'عرض خاص',
    specialOfferMsg: 'احصل على 20% مكافأة على رحلاتك الخمس القادمة',
    paymentSuccess: 'تم الدفع بنجاح',
    paymentSuccessMsg: 'تمت معالجة دفعتك بقيمة 1,400 دج',
    newRideRequest: 'طلب رحلة جديد',
    newRideRequestMsg: 'تم استلام طلب رحلة جديد قريب',
    twoHoursAgo: 'قبل ساعتين',
    yesterday: 'أمس',
    twoDaysAgo: 'قبل يومين',
    threeDaysAgo: 'قبل 3 أيام',
  },

  // Currency - Algerian Dinar
  currency: {
    code: 'DZD',
    symbol: 'دج',
  },

  // Permissions
  permissions: {
    cameraDeniedTitle: 'صلاحية الكاميرا مطلوبة',
    cameraDeniedMessage: 'فعّل صلاحية الكاميرا من إعدادات الجهاز لالتقاط الوثائق والصور الشخصية.',
    photoLibraryDeniedTitle: 'صلاحية الصور مطلوبة',
    photoLibraryDeniedMessage: 'فعّل صلاحية مكتبة الصور من إعدادات الجهاز لرفع الوثائق.',
    failedPickImage: 'فشل اختيار الصورة. يرجى المحاولة مرة أخرى.',
    failedTakePhoto: 'فشل التقاط الصورة. يرجى المحاولة مرة أخرى.',
  },

  // Onboarding completion flow
  onboardingComplete: {
    title: 'اكتمل التسجيل',
    description: 'تم إرسال وثائقك ومعلومات مركبتك. مرحباً بك في وصالني!',
    skipTitle: 'تخطي الرفع',
    skipDescription: 'وضع الاختبار: سيتم اعتبار رفع الوثائق اختياريًا. هل تريد المتابعة إلى الصفحة الرئيسية؟',
  },
} as const;

export default arStrings;
