// English (LTR) - Algeria Localization
export const enStrings = {
  appName: 'WASSELNI',

  // Auth
  auth: {
    enterTheFleet: 'Enter\nthe fleet.',
    authenticateBiometric: 'Authenticate via secure biometric link to access your vehicle, active route assignments, and earnings portfolio.',
    sensorActive: 'Sensor Active',
    tapScanner: 'Tap scanner to verify identity',
    orAuthenticateVia: 'Or Authenticate Via',
    continue: 'Continue',
    verifyIdentity: 'Verify\nIdentity.',
    enterMobileNumber: 'Enter your mobile number to receive a secure one-time passcode.',
    resendCodeIn: 'Resend code in',
    resendCode: 'Resend Code',
    verify: 'Verify',
  },

  // Onboarding
  onboarding: {
    identityVerification: 'Identity Verification',
    basics: 'Basics',
    identity: 'Identity',
    vehicle: 'Vehicle',
    personalInformation: 'Personal Information',
    fullLegalName: 'Full Legal Name',
    asItAppearsOnLicense: 'As it appears on your license',
    emailAddress: 'Email Address',
    youAtDomain: 'you@domain.com',
    homeAddress: 'Home Address',
    streetAddress: 'Street Address',
    city: 'City',
    zip: 'Zip',
    driversLicense: "Driver's License",
    uploadClearImages: 'Upload clear, well-lit images of your official ID.',
    frontSide: 'Front Side',
    backSide: 'Back Side',
    livenessCheck: 'Liveness Check',
    takeQuickSelfie: 'Take a quick selfie to match your ID.',
    captureSelfie: 'Capture Selfie',
    saveDraft: 'Save Draft',
    continueToVehicle: 'Continue to Vehicle',
    vehicleIdentity: 'Vehicle\nIdentity.',
    precisionParamount: 'Precision is paramount. Register your vehicle details to ensure a seamless experience for our clientele.',
    makeAndModel: 'Make & Model',
    make: 'Make',
    makePlaceholder: 'e.g., Toyota',
    model: 'Model',
    modelPlaceholder: 'e.g., Camry',
    year: 'Year',
    yearPlaceholder: 'e.g., 2024',
    licensePlate: 'License Plate',
    licensePlatePlaceholder: 'e.g., ABC-1234',
    documentation: 'Documentation',
    uploadClearCopies: 'Upload clear, legible copies of your current documents.',
    proofOfInsurance: 'Proof of Insurance',
    tapToUpload: 'Tap to upload file',
    tapToUploadFile: 'Tap to upload file',
    vehicleRegistration: 'Vehicle Registration',
    continueToBackgroundCheck: 'Continue to Background Check',
    step2Of4: 'Step 2 of 4',
  },

  // Main
  main: {
    readyToDrive: 'Ready to Drive?',
    goOnline: 'Go Online',
    goOffline: 'Go Offline',
    highDemand: 'High demand in your area right now.',
    todaysEarnings: "Today's Earnings",
    todayEarnings: "Today's Earnings",
    vsYesterday: 'vs yesterday',
    currentRating: 'Current Rating',
    tripsCompleted: 'Trips Completed',
    home: 'Home',
    activity: 'Activity',
    wallet: 'Wallet',
    profile: 'Profile',
    opportunities: 'Opportunities',
    highDemandDowntown: 'High Demand: Downtown',
    slideForEmergency: 'Slide for Emergency',
    earnings: 'Earnings',
    trips: 'Trips',
    safety: 'Safety',
  },

  // Ride Request
  rideRequest: {
    seconds: 'Seconds',
    blackSUV: 'Economy',
    premiumRider: 'Verified Rider',
    pickup: 'Pickup',
    minsAway: 'Mins Away',
    estFare: 'Est. Fare',
    trip: 'trip',
    reject: 'Reject',
    acceptRide: 'Accept Ride',
  },

  // Ride Navigation
  rideNavigation: {
    pickup: 'Pickup',
    dropoff: 'Dropoff',
    fare: 'Fare',
    distance: 'Distance',
    eta: 'ETA',
    completeRide: 'Complete Ride',
    cancelRide: 'Cancel Ride',
    cancelConfirm: 'Are you sure you want to cancel this ride?',
    rideCompleted: 'Ride completed',
    rideCompletedDescription: 'Earnings have been added to your wallet.',
    noActiveRide: 'No active ride',
  },

  // Earnings
  earnings: {
    title: 'Earnings',
    balance: 'Driver Balance',
    availableBalance: 'Available balance & history',
    cashOutNow: 'Cash Out',
    withdraw: 'Withdraw',
    tripEarnings: 'Trip Earnings',
    tips: 'Tips',
    bonuses: 'Bonuses',
    recentActivity: 'Recent Activity',
    viewAll: 'View All Activity',
    tripTo: 'Trip to',
    includesTip: 'Includes tip',
    weeklyPayout: 'Weekly Payout',
    processed: 'Processed',
    paymentMethods: 'Payment Methods',
    defaultCard: 'Bank Card',
    cashPayment: 'Cash',
    default: 'Default',
    addNewMethod: 'Add New Method',
    addFunds: 'Add Funds',
  },

  // Trip History
  tripHistory: {
    title: 'Trip History',
    reviewPerformance: 'Review your past performance and earnings.',
    weeklyEarnings: 'Weekly Earnings',
    trips: 'Trips',
    onlineHours: 'Online Hours',
    vsLastWeek: 'vs last week',
    performance: 'Performance',
    acceptanceRate: 'Acceptance Rate',
    cancellationRate: 'Cancellation Rate',
    recentTrips: 'Recent Trips',
    filter: 'Filter',
    luxeBlack: 'Luxe Black',
    luxeStandard: 'Luxe Standard',
    luxeSUV: 'Luxe SUV',
    loadMoreTrips: 'Load More Trips',
  },

  // Common
  common: {
    save: 'Save',
    edit: 'Edit',
    delete: 'Delete',
    cancel: 'Cancel',
    confirm: 'Confirm',
    back: 'Back',
    next: 'Next',
    done: 'Done',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    retry: 'Retry',
  },

  // Drafts
  drafts: {
    title: 'Drafts',
    subtitle: 'Your saved applications',
    personalInfoDraft: 'Personal Information',
    savedYesterday: 'Saved yesterday',
    noDrafts: 'No drafts yet',
    noDraftsDescription: 'Start a new application to get going',
    startNewApplication: 'Start New Application',
  },

  // Settings
  settings: {
    title: 'Account',
    rating: 'Rating',
    safetySecurity: 'Safety & Security',
    twoFactor: 'Two-Factor Authentication',
    twoFactorDesc: 'Secure your account with SMS codes',
    on: 'On',
    off: 'Off',
    emergencyContacts: 'Emergency Contacts',
    emergencyContactsDesc: 'Manage your trusted contacts',
    preferences: 'Preferences',
    pushNotifications: 'Push Notifications',
    pushNotificationsDesc: 'Trip updates and promotions',
    language: 'Language',
    english: 'English',
    arabic: 'العربية',
    selectLanguage: 'Select Language',
    cancel: 'Cancel',
    supportLegal: 'Support & Legal',
    helpCenter: 'Help Center',
    termsPrivacy: 'Terms & Privacy',
    logOut: 'Log Out',
  },

  // Terms of Service
  termsOfService: {
    title: 'Terms of Service',
    lastUpdated: 'Last updated: January 2024',
    intro: 'By using Wasselni, you agree to these terms. Please read them carefully.',
    acceptance: 'Acceptance of Terms',
    acceptanceText: 'By accessing or using our service, you agree to be bound by these terms.',
    userResponsibilities: 'User Responsibilities',
    responsibilityText: 'You agree to use our service responsibly and in accordance with applicable laws.',
    paymentTerms: 'Payment Terms',
    paymentText: 'Payment is processed at the end of each ride. You agree to pay all applicable fees.',
    cancellation: 'Cancellation Policy',
    cancellationText: 'You may cancel your ride at any time before pickup without charge.',
  },

  // Help
  help: {
    title: 'Help & Support',
    subtitle: 'How can we help you?',
    faq: 'Frequently Asked Questions',
    paymentIssues: 'Payment Issues',
    rideIssues: 'Ride Issues',
    safetyConcerns: 'Safety Concerns',
    contactSupport: 'Need immediate help?',
    callSupport: 'Call Support',
  },

  // Notifications
  notifications: {
    title: 'Notifications',
    preferences: 'Notification Preferences',
    history: 'Notification History',
    rideUpdates: 'Ride Updates',
    rideUpdatesDesc: 'Get notified about your ride status',
    promotions: 'Promotions',
    promotionsDesc: 'Receive special offers and bonuses',
    messages: 'Messages',
    messagesDesc: 'Rider and support messages',
    accountActivity: 'Account Activity',
    accountActivityDesc: 'Security and account updates',
    rideCompleted: 'Ride Completed',
    rideCompletedMsg: 'Your ride to the airport was completed',
    specialOffer: 'Special Offer',
    specialOfferMsg: 'Get 20% bonus on your next 5 rides',
    paymentSuccess: 'Payment Successful',
    paymentSuccessMsg: 'Your payment of 1,400 DA was processed',
    newRideRequest: 'New Ride Request',
    newRideRequestMsg: 'A new ride request was received nearby',
    twoHoursAgo: '2 hours ago',
    yesterday: 'Yesterday',
    twoDaysAgo: '2 days ago',
    threeDaysAgo: '3 days ago',
  },

  // Currency - Algerian Dinar
  currency: {
    code: 'DZD',
    symbol: 'DA',
  },

  // Permissions
  permissions: {
    cameraDeniedTitle: 'Camera access required',
    cameraDeniedMessage: 'Enable camera access in your device settings to capture documents and selfies.',
    photoLibraryDeniedTitle: 'Photo access required',
    photoLibraryDeniedMessage: 'Enable photo library access in your device settings to upload documents.',
    failedPickImage: 'Failed to pick image. Please try again.',
    failedTakePhoto: 'Failed to take photo. Please try again.',
  },

  // Onboarding completion flow
  onboardingComplete: {
    title: 'Onboarding Complete',
    description: 'Your documents and vehicle information have been submitted. Welcome to Wasselni!',
    skipTitle: 'Skip Uploads',
    skipDescription: 'Testing mode: document uploads will be marked as optional. Continue to the dashboard?',
  },
} as const;

export default enStrings;
