// English (LTR) - Algeria Localization
export const enStrings = {
  appName: 'WASSELNI',

  // Auth
  auth: {
    enterTheFleet: 'Enter\nthe fleet.',
    authenticateBiometric: 'Authenticate via secure biometric link to access your vehicle, active route assignments, and earnings portfolio.',
    sensorActive: 'Sensor Active',
    tapScanner: 'Tap scanner to verify identity',
    orAuthenticateVia: 'Or Authenticate Via',
    continue: 'Continue',
    verifyIdentity: 'Verify\nIdentity.',
    enterMobileNumber: 'Enter your mobile number to receive a secure one-time passcode.',
    resendCodeIn: 'Resend code in',
    resendCode: 'Resend Code',
    verify: 'Verify',
  },

  // Onboarding
  onboarding: {
    identityVerification: 'Identity Verification',
    basics: 'Basics',
    identity: 'Identity',
    vehicle: 'Vehicle',
    personalInformation: 'Personal Information',
    fullLegalName: 'Full Legal Name',
    asItAppearsOnLicense: 'As it appears on your license',
    emailAddress: 'Email Address',
    youAtDomain: 'you@domain.com',
    homeAddress: 'Home Address',
    streetAddress: 'Street Address',
    city: 'City',
    zip: 'Zip',
    driversLicense: "Driver's License",
    uploadClearImages: 'Upload clear, well-lit images of your official ID.',
    frontSide: 'Front Side',
    backSide: 'Back Side',
    livenessCheck: 'Liveness Check',
    takeQuickSelfie: 'Take a quick selfie to match your ID.',
    captureSelfie: 'Capture Selfie',
    saveDraft: 'Save Draft',
    continueToVehicle: 'Continue to Vehicle',
    vehicleIdentity: 'Vehicle\nIdentity.',
    precisionParamount: 'Precision is paramount. Register your vehicle details to ensure a seamless experience for our clientele.',
    makeAndModel: 'Make & Model',
    make: 'Make',
    makePlaceholder: 'e.g., Toyota',
    model: 'Model',
    modelPlaceholder: 'e.g., Camry',
    year: 'Year',
    yearPlaceholder: 'e.g., 2024',
    licensePlate: 'License Plate',
    licensePlatePlaceholder: 'e.g., ABC-1234',
    documentation: 'Documentation',
    uploadClearCopies: 'Upload clear, legible copies of your current documents.',
    proofOfInsurance: 'Proof of Insurance',
    tapToUpload: 'Tap to upload file',
    tapToUploadFile: 'Tap to upload file',
    vehicleRegistration: 'Vehicle Registration',
    continueToBackgroundCheck: 'Continue to Background Check',
    step2Of4: 'Step 2 of 4',
  },

  // Main
  main: {
    readyToDrive: 'Ready to Drive?',
    goOnline: 'Go Online',
    goOffline: 'Go Offline',
    highDemand: 'High demand in your area right now.',
    todaysEarnings: "Today's Earnings",
    todayEarnings: "Today's Earnings",
    vsYesterday: 'vs yesterday',
    currentRating: 'Current Rating',
    tripsCompleted: 'Trips Completed',
    home: 'Home',
    activity: 'Activity',
    wallet: 'Wallet',
    profile: 'Profile',
    opportunities: 'Opportunities',
    highDemandDowntown: 'High Demand: Downtown',
    slideForEmergency: 'Slide for Emergency',
    earnings: 'Earnings',
    trips: 'Trips',
    safety: 'Safety',
  },

  // Ride Request
  rideRequest: {
    seconds: 'Seconds',
    blackSUV: 'Black SUV',
    premiumRider: 'Premium Rider',
    pickup: 'Pickup',
    minsAway: 'Mins Away',
    estFare: 'Est. Fare',
    trip: 'trip',
    reject: 'Reject',
    acceptRide: 'Accept Ride',
  },

  // Earnings
  earnings: {
    title: 'Earnings',
    availableBalance: 'Available balance & history',
    cashOutNow: 'Cash Out Now',
    tripEarnings: 'Trip Earnings',
    tips: 'Tips',
    bonuses: 'Bonuses',
    recentActivity: 'Recent Activity',
    viewAll: 'View All',
    tripTo: 'Trip to',
    includesTip: 'Includes',
    weeklyPayout: 'Weekly Payout',
    processed: 'Processed',
  },

  // Trip History
  tripHistory: {
    title: 'Trip History',
    reviewPerformance: 'Review your past performance and earnings.',
    weeklyEarnings: 'Weekly Earnings',
    trips: 'Trips',
    onlineHours: 'Online Hours',
    vsLastWeek: 'vs last week',
    performance: 'Performance',
    acceptanceRate: 'Acceptance Rate',
    cancellationRate: 'Cancellation Rate',
    recentTrips: 'Recent Trips',
    filter: 'Filter',
    luxeBlack: 'Luxe Black',
    luxeStandard: 'Luxe Standard',
    luxeSUV: 'Luxe SUV',
    loadMoreTrips: 'Load More Trips',
  },

  // Common
  common: {
    save: 'Save',
    edit: 'Edit',
    delete: 'Delete',
    cancel: 'Cancel',
    confirm: 'Confirm',
    back: 'Back',
    next: 'Next',
    done: 'Done',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    retry: 'Retry',
  },

  // Drafts
  drafts: {
    title: 'Drafts',
    subtitle: 'Your saved applications',
    personalInfoDraft: 'Personal Information',
    savedYesterday: 'Saved yesterday',
    noDrafts: 'No drafts yet',
    noDraftsDescription: 'Start a new application to get going',
    startNewApplication: 'Start New Application',
  },

  // Currency - Algerian Dinar
  currency: {
    code: 'DZD',
    symbol: 'DA',
  },
} as const;

export default enStrings;
